name: Build and Push presigned URL Docker Image

on:
  workflow_call:
   secrets:
      token:
        required: true

##permission can be added at job level or workflow level   

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:

          role-to-assume: arn:aws:iam::496051641293:role/aws-role-aadharsh #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-central-1 # Replace with your AWS region, e.g., us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
       
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./PresignedUrl/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/presigned-url:latest:latest

      #  # deploy
      # - name: Deploy image to lambda function
      #   env:
      #     tags: ${{ steps.login-ecr.outputs.registry }}/presigned-url:latest:latest
      #   run: |
      #     aws lambda update-function-code --function-name presigned-url --image-uri $tags
